<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DevQuestions.Application\DevQuestions.Application.csproj" />
    <ProjectReference Include="..\DevQuestions.Contracts\DevQuestions.Contracts.csproj" />
    <ProjectReference Include="..\DevQuestions.Domain\DevQuestions.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Comments\" />
  </ItemGroup>
</Project>