<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DevQuestions.Contracts\DevQuestions.Contracts.csproj" />
    <ProjectReference Include="..\DevQuestions.Domain\DevQuestions.Domain.csproj" />
    <ProjectReference Include="..\DevQuestions.Presenters\DevQuestions.Presenters.csproj" />
  </ItemGroup>
</Project>